// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRYBTDjSZCp2mDXJpPQEHjpObbm9gZDWk',
    appId: '1:892279917255:web:44519344c9358363ed4ce2',
    messagingSenderId: '892279917255',
    projectId: 'ashish-interbuild',
    authDomain: 'ashish-interbuild.firebaseapp.com',
    storageBucket: 'ashish-interbuild.firebasestorage.app',
    measurementId: 'G-H9C634T787',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnhl-tn5i6bjvSvPANuw7pjtrvcmfHYCo',
    appId: '1:892279917255:android:bf063902d1f8cf96ed4ce2',
    messagingSenderId: '892279917255',
    projectId: 'ashish-interbuild',
    storageBucket: 'ashish-interbuild.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2n-tqsLL4_Bb1CE_pCrNT_29P3-jFYU',
    appId: '1:892279917255:ios:d3c0559d30c71d49ed4ce2',
    messagingSenderId: '892279917255',
    projectId: 'ashish-interbuild',
    storageBucket: 'ashish-interbuild.firebasestorage.app',
    iosBundleId: 'com.quick.ashishinterbuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO2n-tqsLL4_Bb1CE_pCrNT_29P3-jFYU',
    appId: '1:892279917255:ios:d3c0559d30c71d49ed4ce2',
    messagingSenderId: '892279917255',
    projectId: 'ashish-interbuild',
    storageBucket: 'ashish-interbuild.firebasestorage.app',
    iosBundleId: 'com.quick.ashishinterbuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRYBTDjSZCp2mDXJpPQEHjpObbm9gZDWk',
    appId: '1:892279917255:web:59b4dc3ef4d21b0ded4ce2',
    messagingSenderId: '892279917255',
    projectId: 'ashish-interbuild',
    authDomain: 'ashish-interbuild.firebaseapp.com',
    storageBucket: 'ashish-interbuild.firebasestorage.app',
    measurementId: 'G-LVEJLK0GBQ',
  );
}
